#! /bin/sh

#=====================#
#   Launch programs   #
#=====================#

sxhkd &
$HOME/.config/polybar/launch.sh &

#==============#
#   Monitors   #
#==============#

# Odd workspaces on left monitor, even workspaces on right monitor
bspc monitor VGA-1 -d 1 3 5 7 9 
bspc monitor HDMI-1 -d 2 4 6 8 10 

#===========#
#   bspwm   #
#===========#

bspc config border_width          2
bspc config focused_border_color  "#0099ff"

bspc config window_gap      5
bspc config top_padding     0
bspc config bottom_padding  0

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      true

#===========#
#   Mouse   #
#===========#

bspc config click_to_focus          none
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true    
bspc config pointer_follows_monitor true
