#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh &

bspc monitor VGA-1 -d 1 3 5 7 9 
bspc monitor HDMI-1 -d 2 4 6 8 10 

bspc config border_width            2
bspc config window_gap              5

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
